### PR TITLE
Update gh actions

### PR DESCRIPTION
**Pull request by olivroy**
Also, improve website look.

You can also consider adding favicons using `pkgdown::build_favicons()`.

### CODE REVIEW

**Comment by torfason** [comment]
Hi, thanks for the contribution. I very much appreciate some help in this area since I'm not a great expert on `pkdown` or GitHub Pages. I've built the new site on my personal fork and am all for the new and lighter theme, as well as the favicons:

- https://torfason.github.io/import/

To be compared with the main site:

- https://import.rticulate.org/

There are a few issues that I would like to see fixed before pushing to the `main` branch:

- The [Get started](https://torfason.github.io/import/articles/import.html) page now has an extra icon. Do you know how it might be possible to get rid of this without also getting rid of the Icon when viewing it as the [README](https://github.com/torfason/import/tree/x/docs) of the repo itself?
- Building the site locally (see the [build_and_release_process.R](https://github.com/torfason/import/blob/x/docs/build/build_and_release_process.R)) creates local changes, specifically some files with extra icon resolutions get created. Could you add those to the ignore list so that they don't get added to the repo? A clean checkout should generally stay clean even though it is built.
- If you have any more good ideas for improving the site, feel free to suggest them, the site could definitely use some attention :-)
- Once we have the final version of this, it would be great if you could squash your branch into a single commit, to keep the main branch clean for future maintenance. Of course, I could also squash it myself, but then the original contributor would not be documented.

Best, Magnus

**Comment by olivroy** [comment]
> Hi, thanks for the contribution. I very much appreciate some help in this area since I'm not a great expert on `pkdown` or GitHub Pages. I've built the new site on my personal fork and am all for the new and lighter theme, as well as the favicons:
> 
> * https://torfason.github.io/import/ vs main https://import.rticulate.org/

That is a great initiative!


> * The [Get started](https://torfason.github.io/import/articles/import.html) page now has an extra icon. Do you know how it might be possible to get rid of this without also getting rid of the Icon when viewing it as the [README](https://github.com/torfason/import/tree/x/docs) of the repo itself?

Fixed! just removed the logo, as pkgdown adds a logo on the top right by default.

> * Building the site locally (see the [build_and_release_process.R](https://github.com/torfason/import/blob/x/docs/build/build_and_release_process.R)) creates local changes, specifically some files with extra icon resolutions get created. Could you add those to the ignore list so that they don't get added to the repo? A clean checkout should generally stay clean even though it is built.

You could remove `devtools::build_site()` from your release script. As the site seems to be built Your release script should not be affected from what I understand. However, you could remove the `build These files appear in the `docs/` directory which is RBuildignored.  and gitignored, the site is deployed from the gh-pages branch. Please clarify what you mean here! 


> * Once we have the final version of this, it would be great if you could squash your branch into a single commit, to keep the main branch clean for future maintenance. Of course, I could also squash it myself, but then the original contributor would not be documented.

It is possible to squash and merge on GitHub. On the merge pull request button, you can select Squash. but I do not mind if my name does not appear, it is a very small contribution.
image

**Comment by olivroy** [comment]
I just updated the gh actions to latest. The workflows are now simpler and use pak under the hood. `usethis::use_github_action("check-standard")` and `usethis::use_github_action("pkgdown")`.

**Comment by torfason** [comment]
I added all the changes apart from the actions, after squashing the commits for a cleaner history, see #91. I got an error on the actions, something to do with the caching step, so I decided to postpone them for now. So I'll close this PR, we can do another PR on the `dev` branch for updating the actions. I added you to the contributor's list, thanks for the updates!

**Pull request closed without merging**
